//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///    Clase de recurso fuertemente tipado para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///    Devuelve la instancia ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///    búsquedas de recursos usando esta clase de recursos fuertemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a How to write number .
        /// </summary>
        internal static string CabeceraNumeroFormateado2 {
            get {
                return ResourceManager.GetString("CabeceraNumeroFormateado2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a  in polish?.
        /// </summary>
        internal static string CabeceraNumeroFormateado3 {
            get {
                return ResourceManager.GetString("CabeceraNumeroFormateado3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Digits from zero to nine are rendered by specific words, namely zero [0], jeden [1], dwa [2], trzy [3], cztery [4], pięć [5], sześć [6], siedem [7], osiem [8], and dziewięć [9]..
        /// </summary>
        internal static string CardinalNotas1 {
            get {
                return ResourceManager.GetString("CardinalNotas1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Tens are formed by stating the multiplier digit before a variation of the word for ten (dziesięć, dzieścia, dzieści or dziesiąt), except for ten itself: dziesięć [10], dwadzieścia [20], trzydzieści [30], czterdzieści [40], pięćdziesiąt [50], sześćdziesiąt [60], siedemdziesiąt [70], osiemdziesiąt [80], and dziewięćdziesiąt [90]..
        /// </summary>
        internal static string CardinalNotas2 {
            get {
                return ResourceManager.GetString("CardinalNotas2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Teens are formed by starting with the unit, directly followed by naście, from na (and) and dziesięć (ten): jedenaście [11] (literally, one and ten), dwanaście [12], trzynaście [13], czternaście [14], piętnaście [15], szesnaście [16], siedemnaście [17], osiemnaście [18], and dziewiętnaście [19]..
        /// </summary>
        internal static string CardinalNotas3 {
            get {
                return ResourceManager.GetString("CardinalNotas3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Compound numbers above twenty are formed by starting with the ten, then the unit separated with a space (e.g.: dwadzieścia jeden [21], pięćdziesiąt trzy [53])..
        /// </summary>
        internal static string CardinalNotas4 {
            get {
                return ResourceManager.GetString("CardinalNotas4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Hundreds are formed by stating the multiplier digit before a form of the word for hundred (ście, sta or set) with no space, except for one hundred: sto [100], dwieście [200], trzysta [300], czterysta [400], pięćset [500], sześćset [600], siedemset [700], osiemset [800], and dziewięćset [900]..
        /// </summary>
        internal static string CardinalNotas5 {
            get {
                return ResourceManager.GetString("CardinalNotas5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Thousands are formed by stating the multiplier digit before a form of the word for thousand (tysiąc, tysiące or tysięcy) separated with a space, except for one thousand: tysiąc [1,000], dwa tysiące [2,000], trzy tysiące [3,000], cztery tysiące [4,000], pięć tysięcy [5,000], sześć tysięcy [6,000], siedem tysięcy [7,000], osiem tysięcy [8,000], and dziewięć tysięcy [9,000]..
        /// </summary>
        internal static string CardinalNotas6 {
            get {
                return ResourceManager.GetString("CardinalNotas6", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a The Polish language uses the long scale naming convention. .
        /// </summary>
        internal static string CardinalNotas7 {
            get {
                return ResourceManager.GetString("CardinalNotas7", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Cardinal.
        /// </summary>
        internal static string CardinalTipo {
            get {
                return ResourceManager.GetString("CardinalTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Decimal.
        /// </summary>
        internal static string DecimalTipo {
            get {
                return ResourceManager.GetString("DecimalTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Example.
        /// </summary>
        internal static string Ejemplos {
            get {
                return ResourceManager.GetString("Ejemplos", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a ERROR.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Fractional.
        /// </summary>
        internal static string FraccionarioTipo {
            get {
                return ResourceManager.GetString("FraccionarioTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a The cardinal, ordinal, partitive, multiplicative, collective text is shown and its Roman numeral and more... corresponding to the written number..
        /// </summary>
        internal static string Lista1 {
            get {
                return ResourceManager.GetString("Lista1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a The numerator is too large..
        /// </summary>
        internal static string Lista10 {
            get {
                return ResourceManager.GetString("Lista10", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a The decimal part is too large..
        /// </summary>
        internal static string Lista11 {
            get {
                return ResourceManager.GetString("Lista11", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a &lt;b&gt;DON&apos;T write a number with letters, except the Roman numeral&lt;/b&gt;..
        /// </summary>
        internal static string Lista12 {
            get {
                return ResourceManager.GetString("Lista12", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a The divisor is too large..
        /// </summary>
        internal static string Lista13 {
            get {
                return ResourceManager.GetString("Lista13", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a The exponent is too large..
        /// </summary>
        internal static string Lista14 {
            get {
                return ResourceManager.GetString("Lista14", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Unknown error..
        /// </summary>
        internal static string Lista15 {
            get {
                return ResourceManager.GetString("Lista15", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Please, send an email to tulengua.es@gmal.com with the number that you typed..
        /// </summary>
        internal static string Lista16 {
            get {
                return ResourceManager.GetString("Lista16", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a We will try to solve as soon as possible..
        /// </summary>
        internal static string Lista17 {
            get {
                return ResourceManager.GetString("Lista17", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a We apologize for any inconvenience..
        /// </summary>
        internal static string Lista18 {
            get {
                return ResourceManager.GetString("Lista18", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a &lt;b&gt;Currency symbols (€, £, ¥, etc.) are not supported for this language.&lt;/b&gt; We are working on it ....
        /// </summary>
        internal static string Lista19 {
            get {
                return ResourceManager.GetString("Lista19", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Write a number without comma or decimal point for the thousands or millions:.
        /// </summary>
        internal static string Lista2 {
            get {
                return ResourceManager.GetString("Lista2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a The number, exponent or decimal part may be too large..
        /// </summary>
        internal static string Lista20 {
            get {
                return ResourceManager.GetString("Lista20", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a You can write amounts in &lt;b&gt; euros &lt;/b&gt; with the € symbol or the word &lt;i&gt; euros &lt;/i&gt;:.
        /// </summary>
        internal static string Lista21 {
            get {
                return ResourceManager.GetString("Lista21", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a You can write amounts in &lt;b&gt;pesos&lt;/b&gt; with the $ symbol or the word &lt;i&gt;pesos&lt;/i&gt;:.
        /// </summary>
        internal static string Lista22 {
            get {
                return ResourceManager.GetString("Lista22", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a You can write amounts in &lt;b&gt;dólares&lt;/b&gt; with the $ symbol or the word &lt;i&gt;dólares&lt;/i&gt;:.
        /// </summary>
        internal static string Lista23 {
            get {
                return ResourceManager.GetString("Lista23", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a You can separate the thousands or millions with a blank space:.
        /// </summary>
        internal static string Lista3 {
            get {
                return ResourceManager.GetString("Lista3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a In decimal, you can use a decimal point or comma:.
        /// </summary>
        internal static string Lista4 {
            get {
                return ResourceManager.GetString("Lista4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a You can write fractions with the bar:.
        /// </summary>
        internal static string Lista5 {
            get {
                return ResourceManager.GetString("Lista5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a In scientific notation, you can use the letter E without spaces:.
        /// </summary>
        internal static string Lista6 {
            get {
                return ResourceManager.GetString("Lista6", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a For Roman numeral, you can write in capital letter all symbols:.
        /// </summary>
        internal static string Lista7 {
            get {
                return ResourceManager.GetString("Lista7", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a The supported formats for Chinese are as follows:.
        /// </summary>
        internal static string Lista8 {
            get {
                return ResourceManager.GetString("Lista8", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a The number is too large..
        /// </summary>
        internal static string Lista9 {
            get {
                return ResourceManager.GetString("Lista9", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Multiplicative.
        /// </summary>
        internal static string MultiplicativoTipo {
            get {
                return ResourceManager.GetString("MultiplicativoTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Notes.
        /// </summary>
        internal static string Notas {
            get {
                return ResourceManager.GetString("Notas", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Correct Roman numeral.
        /// </summary>
        internal static string NumeroRomanoCorrecto {
            get {
                return ResourceManager.GetString("NumeroRomanoCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Wrong Roman numeral.
        /// </summary>
        internal static string NumeroRomanoIncorrecto {
            get {
                return ResourceManager.GetString("NumeroRomanoIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a All options.
        /// </summary>
        internal static string Opciones {
            get {
                return ResourceManager.GetString("Opciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Ordinal.
        /// </summary>
        internal static string OrdinalTipo {
            get {
                return ResourceManager.GetString("OrdinalTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Reference.
        /// </summary>
        internal static string Referencias {
            get {
                return ResourceManager.GetString("Referencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Roman.
        /// </summary>
        internal static string RomanoTipo {
            get {
                return ResourceManager.GetString("RomanoTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Numerical value.
        /// </summary>
        internal static string ValorNumerico {
            get {
                return ResourceManager.GetString("ValorNumerico", resourceCulture);
            }
        }
    }
}
